# WHY CHOOSE NUMPY. 16TH NOVEMBER, 2021

## Numpy is faster than lists.
This is because numpy uses fixed types.
Numpy integer values are stored as binary values stored as int32 by default.
You can specify if you need int32,int16 or int8.
Anpther advantage of numpy arrays over lists is that there is no typechecking when iterating through each item in the array.

Numpy uses contiguous memory.
All information is next to each other.
1. SIMD VECTOR PROCESSING-Single Instructions Multiple Data. Perfom operations on all items at one time using simple instruction.
2. We can more effectively use our cache. Shorter memory lookups.
3. We can do all list operations on numpy arrays plus more.

## With lists
Integer values store a lot more information.
The int type in Python consists of Object Value, Object Type, Reference Value, and size. Hence takes more space.

Lists contains pointers to items that are stored in different places in the computer's memory. Hence is less fast esp when performing functions on all items at the same time.

## Applications of Numpy

### Mathematics
Matlab Replacement

### Plotting
Matplotlib

### Backend to other libraries
Such as pandas, Connect 4,Digital Photography

### Machine Learning
Very similar to tensor library especially on how they store values.

# ONTO CODE

In [1]:
import numpy as np

## The Basics

### Initialize array

#### 1D Array

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


#### 2D Array

In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


We can create list within a list within a list to create 3D arrays.

#### Get Dimension

In [4]:
a.ndim

1

In [5]:
b.ndim

2

#### Get Shape

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 3)

Shape comes in rows by columns

#### Get Type

In [8]:
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

##### Specify Type

In [10]:
a=np.array([1,2,3], dtype='int16')
a.dtype

dtype('int16')

####  Get Size
Returns Bytes

In [11]:
a.itemsize

2

In [12]:
a=np.array([1,2,3], dtype='int32')
a.itemsize

4

In [13]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b.itemsize

8

#### Get Total Size

##### x.size
We use x.size to get number of elements where x is the array

In [14]:
a.size

3

In [15]:
b.size

6

Total size = a.size*a.itemsize

In [16]:
a.size*a.itemsize

12

In [17]:
b.size*b.itemsize 

48

## Accessing/Changing specific elements,rows, columns e.t.c

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


#### Get a specific element [r , c]

In [19]:
a[1,5]

13

#### Get specific row 

In [20]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

#### Get specific column 

In [22]:
a[:,3]

array([ 4, 11])

In [23]:
a[:,2]

array([ 3, 10])

In [24]:
a[:,0]

array([1, 8])

#### Getting a little fancy [startindex:endindex:stepsize]

In [25]:
a[0,1:6:2]

array([2, 4, 6])

In [26]:
a[0,1:-1:2]

array([2, 4, 6])

#### Changing elements

In [27]:
a[1,5]=20

In [28]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### `Initialize different types of arrays

#### Zeros Matrix

All Zeros matrix

np.zeros(Matrix shape)


In [30]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

Note second bracket when shape is 2d & up

In [31]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [32]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
#Results in error
np.zeros(2,3)

TypeError: Cannot interpret '3' as a data type

#### Ones Matrix

All ones matrix

np.ones(MatrixShape)

Similar theory to zeros

In [34]:
np.ones(2)

array([1., 1.])

In [35]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [36]:
y=np.ones((2,2,3))
print(y)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


Can specify data type in ones matrix

In [37]:
z=np.ones((2,2,3), dtype='int32')
print(z)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [38]:
z.dtype

dtype('int32')

In [39]:
y.dtype

dtype('float64')

#### Full Matrix other number

np.full(shape,number)

In [40]:
np.full((2,2),4343,dtype="float64")

array([[4343., 4343.],
       [4343., 4343.]])

##### use shape of already used variable/matrix

In [41]:
np.full(z.shape,23)

array([[[23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23]]])

<i>You can also use np.full_like(x,y)<br>
Makes new array similar to x in all aspects including dtype

In [42]:
np.full_like(z,23)

array([[[23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23]]], dtype=int32)

### Matrix of random numbers


<b>Random numbers btn 0 & 1 -(decimals)</b><br><br>
use np.random.rand(Matrix shape)

In [43]:
np.random.rand(3,4)

array([[0.22366488, 0.56210486, 0.5975047 , 0.14816624],
       [0.76506764, 0.74810284, 0.96232444, 0.66174797],
       [0.37160985, 0.44260886, 0.60950521, 0.07759771]])

In [44]:
np.random.rand(2,)

array([0.87027474, 0.16100761])

In [45]:
np.random.rand(2,1)

array([[0.19516578],
       [0.75594854]])

Same shape as other array x<br>
Use np.random.random_sample(x.shape)

In [46]:
np.random.random_sample(z.shape)

array([[[0.8044111 , 0.32871964, 0.86469216],
        [0.89864069, 0.63750165, 0.43861496]],

       [[0.07353652, 0.95503627, 0.77679784],
        [0.81352463, 0.90230115, 0.71035478]]])

#### Random Integer Values

use np.random.randint(start number,(end number-<i>optional</i>), size=())

In [47]:
np.random.randint(4, size=(2,3))

array([[3, 2, 3],
       [3, 1, 3]])

In [48]:
np.random.randint(4,23, size=(2,3,6))

array([[[13, 11,  5, 14, 22, 13],
        [12, 21, 22,  9, 17, 18],
        [ 4, 19, 10, 20, 13, 17]],

       [[ 4, 17, 19, 12,  6, 17],
        [ 6,  4, 18, 22,  5, 19],
        [13, 12, 13, 10, 10, 11]]])

#### Identity Matrix

np.identity(x), where x = shape

In [49]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Other useful functions

In [51]:
arr=np.array([[1,2,3]]) #note that its a 2D array
r1=np.repeat(arr,5, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


### Be careful when printing arrays

In [52]:
a=np.array([1,2,3])
b=a
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]


As you can see above, saying b=a means b points in the same location in memory as a<br>
Therefore modifying b modifies a<br>
<b><i>Therefore its advised to use the .copy() function

In [53]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


## Mathematics

Applying a maths operation to an array means that all values in the array are subject to the operation

In [54]:
print(a)

[1 2 3]


In [55]:
a+2

array([3, 4, 5])

In [56]:
a/2

array([0.5, 1. , 1.5])

In [57]:
a*2

array([2, 4, 6])

In [58]:
a**3

array([ 1,  8, 27])

In [59]:
a%2

array([1, 0, 1])

In [60]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

<i><b>For more math</b> https://docs.scipy.org/doc/numpy/reference/routines.math.html</i>

## Linear Algebra

In [61]:
a=np.ones((4,5))
print(a)
b=np.full((5,4),5)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


To multiply matrices x and y, we use <b><i>np.matmul(x,y)</i></b>

In [62]:
np.matmul(a,b)

array([[25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.],
       [25., 25., 25., 25.]])

<b>Find the Determinant</b>

In [63]:
c=np.identity(4)
np.linalg.det(c)

1.0

<i><b>For more linear algebra</b> https://docs.scipy.org/doc/numpy/reference/routines.linalg.html</i>

## Statistics

<i><b>axis=0 refers to columns<br>
    axis=1 refers to rows</b></i>

In [64]:
stats=np.array([[1,2,3,4],[5,6,7,8]])
print(stats)

[[1 2 3 4]
 [5 6 7 8]]


In [65]:
np.min(stats)

1

In [66]:
np.max(stats)

8

In [67]:
np.max(stats,axis=0)

array([5, 6, 7, 8])

In [68]:
np.max(stats,axis=1)

array([4, 8])

In [69]:
np.sum(stats)

36

In [70]:
np.sum(stats, axis=1)

array([10, 26])

In [71]:
np.sum(stats, axis =0)

array([ 6,  8, 10, 12])

## Reogarnizing arrays

#### Changing shape of array

In [72]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### Vertically stacking Vectors

Columns must be equal

In [73]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
np.vstack([a,b,b,b,a])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

#### Horizontally stacking Vectors

Rows must be equal

In [75]:
a=np.zeros((3,4))
b=np.ones((3,3))
z=np.hstack([a,b])
print(z)

[[0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]]


## Miscellaneous

### Load data from file

<b>From txt:</b> np.genfromtxt(filename, delimiter="specifies what separates the values")<br>
<b>Change the filetype:</b> variable.astype(" specifytype <i>e.g int32</i> ")

### Boolean Masking and advanced indexing

In [76]:
z<1

array([[ True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False, False, False],
       [ True,  True,  True,  True, False, False, False]])

In [77]:
z>=1

array([[False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True]])

In [78]:
z[z>=1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
np.any(z>=1,axis=0)

array([False, False, False, False,  True,  True,  True])

In [81]:
np.any(z>=1,axis=1)

array([ True,  True,  True])

In [82]:
np.all(z>=1,axis=0)

array([False, False, False, False,  True,  True,  True])

In [84]:
np.all(z>=1,axis=1)

array([False, False, False])

In [85]:
((z>0)&(z<=1))

array([[False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True],
       [False, False, False, False,  True,  True,  True]])

### You can index with a list in numpy

In [79]:
a=np.array([2,3,4,5,5])
a[[1,4,2]]

array([3, 5, 4])

## EXERCISE

In [90]:
a=np.random.randint(3,100,size=(6,5))
print(a)

[[46 51 69 31 89]
 [56 61 17  9 47]
 [44 58 82 88 95]
 [25 69 28 61 31]
 [87 47 51 85 35]
 [15 69 64 66 74]]


In [93]:
a[[0,1,2,3],[1,2,3,4]] #selecting elements in a diagonal

array([51, 17, 88, 31])

In [97]:
a[[0,4,5],3:]

array([[31, 89],
       [85, 35],
       [66, 74]])